version: '3.8'
services:
   app:
     build: .
     command: python -u wsgi.py
     ports:
       - "5555:5555"
     volumes:
       - .:/app
     links:
       - db
   db:
     image: mongo:latest
     ports:
      - "27017:27017"
     hostname: test_mongodb
     environment:
        - MONGO_INITDB_DATABASE=kuriboh
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass