name: ci - release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitingore'
      - 'docker-compose.yml'
      - 'Dockerfile'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run tests and collect coverage
      run: pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
    
  deploy:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to production
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.SSH_REMOTE_DEPLOY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
